language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "6"
services: mongodb
before_script:
  - mongoimport --db marvel --collection powerlevels --type json --file data/powerlevels.json --jsonArray
script:
  - npm run test
  - npm run test:backend
