export const RECEIVE_POWERLEVELS_ERROR = 'RECEIVE_POWERLEVELS_ERROR';
export const RECEIVE_POWERLEVELS = 'RECEIVE_POWERLEVELS';
export const REQUEST_POWERLEVELS = 'REQUEST_POWERLEVELS';

export const RECEIVE_CHARACTERS_ERROR = 'RECEIVE_CHARACTERS_ERROR';
export const RECEIVE_CHARACTERS = 'RECEIVE_CHARACTERS';
export const REQUEST_CHARACTERS_BY_NAME = 'REQUEST_CHARACTERS_BY_NAME';
