export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const RECEIVE_COUNTRIES = 'RECEIVE_COUNTRIES';
export const REQUEST_COUNTRIES = 'REQUEST_COUNTRIES';

export const RECEIVE_MARVEL_CHARACTERS_ERROR = 'RECEIVE_MARVEL_CHARACTERS_ERROR';
export const RECEIVE_MARVEL_CHARACTERS = 'RECEIVE_MARVEL_CHARACTERS';
export const REQUEST_MARVEL_CHARACTERS_BY_NAME = 'REQUEST_MARVEL_CHARACTERS_BY_NAME';
