export const RECEIVE_MARVEL_POWERLEVELS_ERROR = 'RECEIVE_MARVEL_POWERLEVELS_ERROR';
export const RECEIVE_MARVEL_POWERLEVELS = 'RECEIVE_POWERLEVELS';
export const REQUEST_MARVEL_POWERLEVELS = 'REQUEST_POWERLEVELS';

export const RECEIVE_MARVEL_CHARACTERS_ERROR = 'RECEIVE_MARVEL_CHARACTERS_ERROR';
export const RECEIVE_MARVEL_CHARACTERS = 'RECEIVE_MARVEL_CHARACTERS';
export const REQUEST_MARVEL_CHARACTERS_BY_NAME = 'REQUEST_MARVEL_CHARACTERS_BY_NAME';
