export const RECEIVE_POWERLEVELS_ERROR = '@@marvel/RECEIVE_POWERLEVELS_ERROR';
export const RECEIVE_POWERLEVELS = '@@marvel/RECEIVE_POWERLEVELS';
export const REQUEST_POWERLEVELS = '@@marvel/REQUEST_POWERLEVELS';

export const RECEIVE_CHARACTERS_ERROR = '@@marvel/RECEIVE_CHARACTERS_ERROR';
export const RECEIVE_CHARACTERS = '@@marvel/RECEIVE_CHARACTERS';
export const REQUEST_CHARACTERS_BY_NAME = '@@marvel/REQUEST_CHARACTERS_BY_NAME';
